<?php
	
/*
	Question2Answer 1.4 (c) 2011, Gideon Greenspan

	http://www.question2answer.org/

	
	File: qa-include/qa-lang-options.php
	Version: 1.4
	Date: 2011-06-13 06:42:43 GMT
	Description: Language phrases for all options, as shown in admin center


	This program is free software; you can redistribute it and/or
	modify it under the terms of the GNU General Public License
	as published by the Free Software Foundation; either version 2
	of the License, or (at your option) any later version.
	
	This program is distributed in the hope that it will be useful,
	but WITHOUT ANY WARRANTY; without even the implied warranty of
	MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
	GNU General Public License for more details.

	More about this license: http://www.question2answer.org/license.php
*/

	return array(
		'allow_change_usernames' => 'Allow users with posts to change their usernames:',
		'allow_multi_answers' => 'Allow multiple answers per user:',
		'allow_no_category' => 'Allow questions with no category',
		'allow_no_sub_category' => 'Allow questions with a category but no sub-category',
		'allow_private_messages' => 'Allow users to send each other private messages:',
		'allow_view_q_bots' => 'Allow search engines to view question pages',
		'avatar_allow_gravatar' => 'Allow ^1Gravatar^2 avatars:',
		'avatar_allow_upload' => 'Allow users to upload avatars:',
		'avatar_default_show' => 'Show default avatar:',
		'avatar_profile_size' => 'Size of avatar on user profile page (pixels):',
		'avatar_q_list_size' => 'Size of avatars on question lists (pixels):',
		'avatar_q_page_a_size' => 'Size of avatars on answers (pixels):',
		'avatar_q_page_c_size' => 'Size of avatars on comments (pixels):',
		'avatar_q_page_q_size' => 'Size of avatars on questions (pixels):',
		'avatar_store_size' => 'Maximum size of stored avatars (pixels):',
		'avatar_users_size' => 'Size of avatars on top users page (pixels):',
		'block_bad_words' => 'Censored words (separate by spaces or commas):',
		'block_ips_write' => 'Blocked IP addresses (separate by spaces or commas):',
		'captcha_on_anon_post' => 'Use reCAPTCHA for anonymous posts:',
		'captcha_on_feedback' => 'Use reCAPTCHA on feedback form:',
		'captcha_on_register' => 'Use reCAPTCHA for user registration:',
		'captcha_on_reset_password' => 'Use reCAPTCHA on reset password form:',
		'captcha_on_unconfirmed' => 'Use reCAPTCHA for posts if email not confirmed:',
		'columns_tags' => 'Tags page columns:',
		'columns_users' => 'Users page columns:',
		'comment_on_as' => 'Allow comments on answers:',
		'comment_on_qs' => 'Allow comments on questions:',
		'confirm_user_emails' => 'Request confirmation of user email address:',
		'custom_home_content' => 'Content to display in home page (HTML allowed):',
		'custom_home_heading' => 'Heading to display at top of home page:',
		'custom_welcome' => 'Custom message to include in email sent to new users:',
		'default_privacy' => 'Privacy: Your email address will not be shared or sold to third parties.',
		'default_sidebar' => "Welcome to ^, where you can ask questions and receive answers from other members of the community.",
		'default_suffix' => 'Q&A',
		'do_ask_check_qs' => 'Check for similar questions when asking:',
		'do_complete_tags' => 'Show matching tags while typing:',
		'do_count_q_views' => 'Count the number of question views:',
		'do_example_tags' => 'Show example tags based on question:',
		'do_related_qs' => 'Show related questions on question page:',
		'editor_for_as' => 'Default editor for answers:',
		'editor_for_cs' => 'Default editor for comments:',
		'editor_for_qs' => 'Default editor for questions:',
		'email_privacy' => 'Privacy note for email on all forms (HTML allowed):',
		'feed_for_activity' => 'Feed for recent activity:',
		'feed_for_qa' => 'Feed for recent questions and answers:',
		'feed_for_questions' => 'Feed for recent questions:',
		'feed_for_search' => 'Feeds for search results:',
		'feed_for_tag_qs' => 'Feeds for recent questions with each tag:',
		'feed_for_unanswered' => 'Feed for recent unanswered questions:',
		'feed_full_text' => 'Include full text in feeds:',
		'feed_number_items' => 'Maximum number of items in feeds:',
		'feed_per_category' => 'Feeds for the above in each category:',
		'feedback_email' => 'Email address for admin messages (not shown to users):',
		'feedback_enabled' => 'Provide a form for users to send me feedback',
		'flagging_hide_after' => 'Automatically hide posts which reach:',
		'flagging_notify_every' => 'Email me again after every additional:',
		'flagging_notify_first' => 'Email me first once a post receives:',
		'flagging_of_posts' => 'Allow posts to be flagged as inappropriate:',
		'follow_on_as' => 'Allow new questions to be related to answers:',
		'from_email' => 'Sender address for all administrative messages:',
		'hot_weight_a_age' => 'Relative weight of last answer age for hotness:',
		'hot_weight_answers' => 'Relative weight of number of answers for hotness:',
		'hot_weight_q_age' => 'Relative weight of question age for hotness:',
		'hot_weight_views' => 'Relative weight of number of views for hotness:',
		'hot_weight_votes' => 'Relative weight of votes for hotness:',
		'links_in_new_window' => 'Open entered links in a new window:',
		'logo_height' => 'Height of logo in pixels:',
		'logo_show' => 'Show a logo image in the page header',
		'logo_url' => 'URL of logo (absolute or relative to QA root):',
		'logo_width' => 'Width of logo in pixels:',
		'match_1' => 'Narrowest',
		'match_2' => 'Narrower',
		'match_3' => 'Default',
		'match_4' => 'Wider',
		'match_5' => 'Widest',
		'match_ask_check_qs' => 'Similar questions matching:',
		'match_example_tags' => 'Example tags matching:',
		'match_related_qs' => 'Related questions matching:',
		'max_len_q_title' => 'Maximum characters in question title:',
		'max_num_q_tags' => 'Maximum number of question tags:',
		'max_rate_ip_as' => 'Maximum answers per IP address per hour:',
		'max_rate_ip_cs' => 'Maximum comments per IP address per hour:',
		'max_rate_ip_flags' => 'Maximum flags per IP address per hour:',
		'max_rate_ip_logins' => 'Maximum login attempts per IP address per hour:',
		'max_rate_ip_messages' => 'Maximum private messages per IP address per hour:',
		'max_rate_ip_qs' => 'Maximum questions per IP address per hour:',
		'max_rate_ip_uploads' => 'Maximum uploads per IP address per hour:',
		'max_rate_ip_votes' => 'Maximum votes per IP address per hour:',
		'max_rate_user_as' => 'Maximum answers per user per hour:',
		'max_rate_user_cs' => 'Maximum comments per user per hour:',
		'max_rate_user_flags' => 'Maximum flags per user per hour:',
		'max_rate_user_messages' => 'Maximum private messages per user per hour:',
		'max_rate_user_qs' => 'Maximum questions per user per hour:',
		'max_rate_user_uploads' => 'Maximum uploads per user per hour:',
		'max_rate_user_votes' => 'Maximum votes per user per hour:',
		'min_len_a_content' => 'Minimum characters in answer:',
		'min_len_c_content' => 'Minimum characters in comment:',
		'min_len_q_content' => 'Minimum characters in question body:',
		'min_len_q_title' => 'Minimum characters in question title:',
		'min_num_q_tags' => 'Minimum number of question tags:',
		'neat_urls' => 'URL structure for pages on your site:',
		'notify_admin_q_post' => 'Email me at this address when a question is posted',
		'notify_users_default' => 'Check email notification box by default:',
		'page_size_activity' => 'All activity page length:',
		'page_size_ask_check_qs' => 'Maximum similar questions to show:',
		'page_size_ask_tags' => 'Maximum tag hints to show:',
		'page_size_home' => 'Home page length:',
		'page_size_hot_qs' => 'Hot questions page length:',
		'page_size_qs' => 'Questions page length:',
		'page_size_related_qs' => 'Maximum related questions:',
		'page_size_search' => 'Questions on search page:',
		'page_size_tag_qs' => 'Questions on tag page:',
		'page_size_tags' => 'Tags page length:',
		'page_size_una_qs' => 'Unanswered page length:',
		'page_size_user_posts' => 'Posts on user page:',
		'page_size_users' => 'Users page length:',
		'pages_prev_next' => 'Links to previous/next pages:',
		'permit_admins' => 'Administrators',
		'permit_all' => 'Anybody',
		'permit_block' => 'Blocking or unblocking user or IPs:',
		'permit_confirmed' => 'Registered users with email confirmed',
		'permit_create_admins' => 'Creating administrators:',
		'permit_create_eds_mods' => 'Creating editors and moderators:',
		'permit_create_experts' => 'Creating experts:',
		'permit_editors' => 'Editors, Moderators, Admins',
		'permit_experts' => 'Experts, Editors, Moderators, Admins',
		'permit_moderators' => 'Moderators and Admins',
		'permit_points_confirmed' => 'Registered & email confirmed & enough points',
		'permit_points' => 'Registered users with enough points',
		'permit_see_emails' => 'Viewing user email addresses:',
		'permit_supers' => 'Super Administrators',
		'permit_users' => 'Registered users',
		'place_full_below_content' => 'Full width - Below content',
		'place_full_below_footer' => 'Full width - Below footer',
		'place_full_below_nav' => 'Full width - Below navigation',
		'place_full_top' => 'Full width - Top of page',
		'place_main_below_lists' => 'Main area - Below lists',
		'place_main_below_title' => 'Main area - Below title',
		'place_main_bottom' => 'Main area - Bottom',
		'place_main_top' => 'Main area - Top',
		'place_side_below_categories' => 'Side panel - Below categories',
		'place_side_below_sidebar' => 'Side panel - Below sidebar box',
		'place_side_last' => 'Side panel - Last',
		'place_side_top' => 'Side panel - Top',
		'points_a_selected' => 'Having your answer selected as the best:',
		'points_a_voted_max_gain' => 'Limit from up votes on each answer:',
		'points_a_voted_max_loss' => 'Limit from down votes on each answer:',
		'points_base' => 'Add for all users:',
		'points_multiple' => 'Multiply all points:',
		'points_per_a_voted' => 'Per up/down vote on your answer:',
		'points_per_q_voted' => 'Per up/down vote on your question:',
		'points_post_a' => 'Posting an answer:',
		'points_post_q' => 'Posting a question:',
		'points_q_voted_max_gain' => 'Limit from up votes on each question:',
		'points_q_voted_max_loss' => 'Limit from down votes on each question:',
		'points_select_a' => 'Selecting the best answer for your question:',
		'points_vote_down_a' => 'Voting down an answer:',
		'points_vote_down_q' => 'Voting down a question:',
		'points_vote_up_a' => 'Voting up an answer:',
		'points_vote_up_q' => 'Voting up a question:',
		'q_urls_remove_accents' => 'Remove accents from question URLs:',
		'q_urls_title_length' => 'Question title length in URLs:',
		'recaptcha_private_key' => 'Your reCAPTCHA private key:',
		'recaptcha_public_key' => 'Your reCAPTCHA public key:',
		'show_a_form_immediate' => 'Show answer form immediately:',
		'show_always' => 'Always',
		'show_c_reply_buttons' => 'Show reply buttons for comments:',
		'show_custom_footer' => 'Custom HTML at bottom of every page:',
		'show_custom_header' => 'Custom HTML at top of every page:',
		'show_custom_home' => 'Custom content in home page (instead of Q&A)',
		'show_custom_in_head' => 'Custom HTML in <HEAD> section of every page:',
		'show_custom_sidebar' => 'Custom HTML in sidebar box on every page:',
		'show_custom_sidepanel' => 'Custom HTML in side panel on every page:',
		'show_home_description' => 'Include <META> description for home page:',
		'show_if_no_as' => 'If no answers',
		'show_never' => 'Never',
		'show_selected_first' => 'Move selected answer to the top:',
		'show_url_links' => 'Detect and link URLs in entered text:',
		'show_user_points' => 'Display points next to usernames:',
		'show_user_titles' => 'Display titles next to usernames:',
		'show_view_counts' => 'Show the number of question views:',
		'show_when_created' => 'Display age of user content:',
		'site_language' => 'The language for your site interface:',
		'site_maintenance' => 'Take site down for maintenance',
		'site_theme' => 'The visual theme for your site:',
		'site_title' => 'The name of your website for page titles:',
		'site_url' => 'The URL to use when referring to your site:',
		'sort_answers_by' => 'Sort answers by:',
		'sort_time' => 'Time',
		'sort_votes' => 'Votes',
		'suspend_register_users' => 'Temporarily suspend new user registrations:',
		'tag_separator_comma' => 'Only use comma as a tag separator:',
		'tags_or_categories' => 'Classify questions using:',
		'votes_separated' => 'Show separate up and down votes:',
		'voting_on_as' => 'Allow voting on answers:',
		'voting_on_q_page_only' => 'Allow voting on question page only:',
		'voting_on_qs' => 'Allow voting on questions:',
	);
	

/*
	Omit PHP closing tag to help avoid accidental output
*/